//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 05:53:09 PM IST 
//


package com.sanket.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BenefitsCoordinationRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BenefitsCoordinationRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PayerIdentification" type="{http://www.surescripts.com/messaging}PayerIDType" minOccurs="0"/>
 *         &lt;element name="PayerName" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}ServiceTypeCoded" minOccurs="0"/>
 *         &lt;element name="CardholderID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="ResponsibleParty" type="{http://www.surescripts.com/messaging}OptionalNameType" minOccurs="0"/>
 *         &lt;element name="GroupID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="EffectiveDate" type="{http://www.surescripts.com/messaging}DateType"/>
 *             &lt;element name="ExpirationDate" type="{http://www.surescripts.com/messaging}DateType"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="Consent" type="{http://www.surescripts.com/messaging}ConsentType"/>
 *         &lt;element name="PBMMemberID" type="{http://www.surescripts.com/messaging}an..80" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BenefitsCoordinationRequestType", propOrder = {
    "payerIdentification",
    "payerName",
    "serviceTypeCoded",
    "cardholderID",
    "responsibleParty",
    "groupID",
    "effectiveDate",
    "expirationDate",
    "consent",
    "pbmMemberID"
})
public class BenefitsCoordinationRequestType {

    @XmlElement(name = "PayerIdentification")
    protected PayerIDType payerIdentification;
    @XmlElement(name = "PayerName")
    protected String payerName;
    @XmlElement(name = "ServiceTypeCoded")
    protected String serviceTypeCoded;
    @XmlElement(name = "CardholderID")
    protected String cardholderID;
    @XmlElement(name = "ResponsibleParty")
    protected OptionalNameType responsibleParty;
    @XmlElement(name = "GroupID")
    protected String groupID;
    @XmlElement(name = "EffectiveDate")
    protected DateType effectiveDate;
    @XmlElement(name = "ExpirationDate")
    protected DateType expirationDate;
    @XmlElement(name = "Consent", required = true)
    protected String consent;
    @XmlElement(name = "PBMMemberID")
    protected String pbmMemberID;

    /**
     * Gets the value of the payerIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link PayerIDType }
     *     
     */
    public PayerIDType getPayerIdentification() {
        return payerIdentification;
    }

    /**
     * Sets the value of the payerIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerIDType }
     *     
     */
    public void setPayerIdentification(PayerIDType value) {
        this.payerIdentification = value;
    }

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerName(String value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the serviceTypeCoded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceTypeCoded() {
        return serviceTypeCoded;
    }

    /**
     * Sets the value of the serviceTypeCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceTypeCoded(String value) {
        this.serviceTypeCoded = value;
    }

    /**
     * Gets the value of the cardholderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderID() {
        return cardholderID;
    }

    /**
     * Sets the value of the cardholderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderID(String value) {
        this.cardholderID = value;
    }

    /**
     * Gets the value of the responsibleParty property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalNameType }
     *     
     */
    public OptionalNameType getResponsibleParty() {
        return responsibleParty;
    }

    /**
     * Sets the value of the responsibleParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalNameType }
     *     
     */
    public void setResponsibleParty(OptionalNameType value) {
        this.responsibleParty = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupID(String value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setEffectiveDate(DateType value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setExpirationDate(DateType value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the consent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsent() {
        return consent;
    }

    /**
     * Sets the value of the consent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsent(String value) {
        this.consent = value;
    }

    /**
     * Gets the value of the pbmMemberID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPBMMemberID() {
        return pbmMemberID;
    }

    /**
     * Sets the value of the pbmMemberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPBMMemberID(String value) {
        this.pbmMemberID = value;
    }

}
