//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 05:53:09 PM IST 
//


package com.sanket.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BenefitsCoordinationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BenefitsCoordinationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PayerIdentification" type="{http://www.surescripts.com/messaging}PayerIDType" minOccurs="0"/>
 *         &lt;element name="PayerName" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="CardholderID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="CardHolderName" type="{http://www.surescripts.com/messaging}OptionalNameType" minOccurs="0"/>
 *         &lt;element name="GroupID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BenefitsCoordinationType", propOrder = {
    "payerIdentification",
    "payerName",
    "cardholderID",
    "cardHolderName",
    "groupID"
})
public class BenefitsCoordinationType {

    @XmlElement(name = "PayerIdentification")
    protected PayerIDType payerIdentification;
    @XmlElement(name = "PayerName")
    protected String payerName;
    @XmlElement(name = "CardholderID")
    protected String cardholderID;
    @XmlElement(name = "CardHolderName")
    protected OptionalNameType cardHolderName;
    @XmlElement(name = "GroupID")
    protected String groupID;

    /**
     * Gets the value of the payerIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link PayerIDType }
     *     
     */
    public PayerIDType getPayerIdentification() {
        return payerIdentification;
    }

    /**
     * Sets the value of the payerIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerIDType }
     *     
     */
    public void setPayerIdentification(PayerIDType value) {
        this.payerIdentification = value;
    }

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerName(String value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the cardholderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderID() {
        return cardholderID;
    }

    /**
     * Sets the value of the cardholderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderID(String value) {
        this.cardholderID = value;
    }

    /**
     * Gets the value of the cardHolderName property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalNameType }
     *     
     */
    public OptionalNameType getCardHolderName() {
        return cardHolderName;
    }

    /**
     * Sets the value of the cardHolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalNameType }
     *     
     */
    public void setCardHolderName(OptionalNameType value) {
        this.cardHolderName = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupID(String value) {
        this.groupID = value;
    }

}
