//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 05:53:09 PM IST 
//


package com.sanket.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for HeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="To" type="{http://www.surescripts.com/messaging}QualifiedMailAddressType"/>
 *         &lt;element name="From" type="{http://www.surescripts.com/messaging}QualifiedMailAddressType"/>
 *         &lt;element name="MessageID" type="{http://www.surescripts.com/messaging}an..35M"/>
 *         &lt;element name="RelatesToMessageID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="SentTime" type="{http://www.surescripts.com/messaging}UtcDateType"/>
 *         &lt;element name="Security" type="{http://www.surescripts.com/messaging}SecurityType" minOccurs="0"/>
 *         &lt;element name="SenderSoftware" type="{http://www.surescripts.com/messaging}SenderSoftwareType"/>
 *         &lt;element name="Mailbox" type="{http://www.surescripts.com/messaging}MailboxType" minOccurs="0"/>
 *         &lt;element name="TestMessage" type="{http://www.surescripts.com/messaging}n1" minOccurs="0"/>
 *         &lt;element name="RxReferenceNumber" type="{http://www.surescripts.com/messaging}an..35M" minOccurs="0"/>
 *         &lt;element name="TertiaryIdentifier" type="{http://www.surescripts.com/messaging}an..3" minOccurs="0"/>
 *         &lt;element name="PrescriberOrderNumber" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="DigitalSignature" type="{http://www.surescripts.com/messaging}DigitalSignatureType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderType", propOrder = {
    "to",
    "from",
    "messageID",
    "relatesToMessageID",
    "sentTime",
    "security",
    "senderSoftware",
    "mailbox",
    "testMessage",
    "rxReferenceNumber",
    "tertiaryIdentifier",
    "prescriberOrderNumber",
    "digitalSignature"
})
public class HeaderType {

    @XmlElement(name = "To", required = true)
    protected QualifiedMailAddressType to;
    @XmlElement(name = "From", required = true)
    protected QualifiedMailAddressType from;
    @XmlElement(name = "MessageID", required = true)
    protected String messageID;
    @XmlElement(name = "RelatesToMessageID")
    protected String relatesToMessageID;
    @XmlElement(name = "SentTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sentTime;
    @XmlElement(name = "Security")
    protected SecurityType security;
    @XmlElement(name = "SenderSoftware", required = true)
    protected SenderSoftwareType senderSoftware;
    @XmlElement(name = "Mailbox")
    protected MailboxType mailbox;
    @XmlElement(name = "TestMessage")
    protected String testMessage;
    @XmlElement(name = "RxReferenceNumber")
    protected String rxReferenceNumber;
    @XmlElement(name = "TertiaryIdentifier")
    protected String tertiaryIdentifier;
    @XmlElement(name = "PrescriberOrderNumber")
    protected String prescriberOrderNumber;
    @XmlElement(name = "DigitalSignature")
    protected DigitalSignatureType digitalSignature;

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiedMailAddressType }
     *     
     */
    public QualifiedMailAddressType getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiedMailAddressType }
     *     
     */
    public void setTo(QualifiedMailAddressType value) {
        this.to = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiedMailAddressType }
     *     
     */
    public QualifiedMailAddressType getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiedMailAddressType }
     *     
     */
    public void setFrom(QualifiedMailAddressType value) {
        this.from = value;
    }

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the relatesToMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatesToMessageID() {
        return relatesToMessageID;
    }

    /**
     * Sets the value of the relatesToMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatesToMessageID(String value) {
        this.relatesToMessageID = value;
    }

    /**
     * Gets the value of the sentTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSentTime() {
        return sentTime;
    }

    /**
     * Sets the value of the sentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSentTime(XMLGregorianCalendar value) {
        this.sentTime = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityType }
     *     
     */
    public SecurityType getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityType }
     *     
     */
    public void setSecurity(SecurityType value) {
        this.security = value;
    }

    /**
     * Gets the value of the senderSoftware property.
     * 
     * @return
     *     possible object is
     *     {@link SenderSoftwareType }
     *     
     */
    public SenderSoftwareType getSenderSoftware() {
        return senderSoftware;
    }

    /**
     * Sets the value of the senderSoftware property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderSoftwareType }
     *     
     */
    public void setSenderSoftware(SenderSoftwareType value) {
        this.senderSoftware = value;
    }

    /**
     * Gets the value of the mailbox property.
     * 
     * @return
     *     possible object is
     *     {@link MailboxType }
     *     
     */
    public MailboxType getMailbox() {
        return mailbox;
    }

    /**
     * Sets the value of the mailbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailboxType }
     *     
     */
    public void setMailbox(MailboxType value) {
        this.mailbox = value;
    }

    /**
     * Gets the value of the testMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestMessage() {
        return testMessage;
    }

    /**
     * Sets the value of the testMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestMessage(String value) {
        this.testMessage = value;
    }

    /**
     * Gets the value of the rxReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRxReferenceNumber() {
        return rxReferenceNumber;
    }

    /**
     * Sets the value of the rxReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRxReferenceNumber(String value) {
        this.rxReferenceNumber = value;
    }

    /**
     * Gets the value of the tertiaryIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTertiaryIdentifier() {
        return tertiaryIdentifier;
    }

    /**
     * Sets the value of the tertiaryIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTertiaryIdentifier(String value) {
        this.tertiaryIdentifier = value;
    }

    /**
     * Gets the value of the prescriberOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriberOrderNumber() {
        return prescriberOrderNumber;
    }

    /**
     * Sets the value of the prescriberOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriberOrderNumber(String value) {
        this.prescriberOrderNumber = value;
    }

    /**
     * Gets the value of the digitalSignature property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalSignatureType }
     *     
     */
    public DigitalSignatureType getDigitalSignature() {
        return digitalSignature;
    }

    /**
     * Sets the value of the digitalSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalSignatureType }
     *     
     */
    public void setDigitalSignature(DigitalSignatureType value) {
        this.digitalSignature = value;
    }

}
